spring.application.name=SportSpotServer
# Nom de la base de dades a la memòria RAM
spring.datasource.url=jdbc:h2:mem:sportspotdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=



# Per poder veure  la base de dades des del navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 1. Fem que Hibernate només creï les taules. Això fa que Spring creï les taules automàticament mirant les  classes Java

spring.jpa.hibernate.ddl-auto=update

# 2. ACTIVAR EL CARREGADOR D'SQL 
# Li diem que SEMPRE executi scripts SQL en arrencar
#spring.sql.init.mode=always

# 3.Sincronització
# Obliguem a Spring a esperar que Hibernate creï la taula "usuaris" 
# abans d'intentar fer l'INSERT del fitxer SQL.
spring.jpa.defer-datasource-initialization=true

# 4. Per si de cas el fitxer no es troba, l'especifiquem manualment
spring.sql.init.data-locations=classpath:import.sql